@startuml Invite Volunteer

actor       Organizer
participant System
database    Database
participant SMS_service

Organizer -> System : Нажимает на кнопку\n"Волонтёры"
System  -> Database : Запрос списка\nсвободных волонтёров
Database --> System : Список волонтёров
System --> Organizer: Отобразить список волонтёров
Organizer -> System : Нажимает на конкретного\nволнтёра из списка
System  -> Database : Запрос анкеты волонтёра
Database --> System : Анкета волнтёра
System --> Organizer: Отобразить анкету волонтёра
Organizer -> System : Нажимает на кнопку\n"Пригласить волонтёра"
System  -> Database : Создать приглашение волонтёра на проект
Database -> Database : Создать новую запись

alt#00ffa1 Успешный кейс
    par
    Database --> System : 200 ОК: Приглашение создано
    else
    Database  --> System : Сформировать данные для отправки\nсмс волонтёру о новом приглашении ено на проект
    end
    System --> Organizer: Отобразить успешное создание приглашения
else 
    group#ff005e
    Database  --> System :Ошибка 400 Bad Request
    System --> Organizer: Отображение заглушки с ошибкой 400
    end
end
System -> Database: Данные отправки для Сервиса записываются\nв таблицу "sms"
System -> SMS_service: Отправить смс: Новое приглашение на проект

alt#00ffa1 Успешный кейс
SMS_service --> System: Response 200 "success"
System -> Database: Актуализация данных таблицы "sms"
else Вид ошибки
  group#ff005e Ошибка 400
    SMS_service --> System: : Roquest 400 Validation error
    System -> System : Запись Log-ов
    end
    group#ff005e Ошибка 402
    SMS_service --> System: : Request 402 Not enough money
    System -> System : Запись Log-ов
    end
    group#ff005e Ошибка 404
    SMS_service --> System: : Request 404 Invalid ip-address
    System -> System : Запись Log-ов
   end
end   
@enduml

